spring:
  application:
    name: eureka-server
server:
  port: 8010
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8020/eureka/
  server:
    enable-self-preservation: false
