spring:
  application:
    name: ribbon-consumer
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8020/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000