spring:
  application:
    name: hello-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8020/eureka/
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG