spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CarreyI/springcloud-demo.git
          search-paths: springcloud-config-profile/config-repo
server:
  port: 7070